
# FIXME original picloud response for package_list call
PACKAGES_TO_IGNORE = [
    "ArgImagePlugin", "BaseHTTPServer", "Bastion", "BdfFontFile", 
    "BeautifulSoup", "BeautifulSoupTests", "Bio", "BioSQL", "BmpImagePlugin", 
    "BufrStubImagePlugin", "CDROM", "CGIHTTPServer", "ConfigParser", "ContainerIO", "Cookie",
    "Crypto", "CurImagePlugin", "Cython", "DLFCN", "DcxImagePlugin", "DocXMLRPCServer", "EpsImagePlugin",
    "ExifTags", "FitsStubImagePlugin", "FixTk", "FliImagePlugin", "FontFile", "FpxImagePlugin", "GbrImagePlugin",
    "GdImageFile", "GifImagePlugin", "GimpGradientFile", "GimpPaletteFile", "GribStubImagePlugin", "HTMLParser",
    "Hdf5StubImagePlugin", "IN", "IPython", "IcnsImagePlugin", "IcoImagePlugin", "ImImagePlugin", "Image", "ImageChops",
    "ImageColor", "ImageDraw", "ImageDraw2", "ImageEnhance", "ImageFile", "ImageFileIO", "ImageFilter", "ImageFont",
    "ImageMath", "ImageMode", "ImageOps", "ImagePalette", "ImagePath", "ImageSequence", "ImageShow", "ImageStat", "ImageTransform",
    "ImageWin", "ImtImagePlugin", "IptcImagePlugin", "JpegImagePlugin", "McIdasImagePlugin", "MicImagePlugin", "MimeWriter",
    "MpegImagePlugin", "MspImagePlugin", "MySQLdb", "OleFileIO", "PIL", "PSDraw", "PaletteFile", "PalmImagePlugin", "PcdImagePlugin", 
    "PcfFontFile", "PcxImagePlugin", "PdfImagePlugin", "PixarImagePlugin", "PngImagePlugin", "PpmImagePlugin", "PsdImagePlugin", 
    "Pyrex", "Pyste", "Queue", "SgiImagePlugin", "SimpleHTTPServer", "SimpleXMLRPCServer", "SocketServer", "SpiderImagePlugin", 
    "StringIO", "SunImagePlugin", "TYPES", "TarIO", "TgaImagePlugin", "TiffImagePlugin", "TiffTags", "Tkconstants", "UserDict", 
    "UserList", "UserString", "WalImageFile", "WmfImagePlugin", "XVThumbImagePlugin", "XbmImagePlugin", "XpmImagePlugin", "__future__", 
    "__init__", "__phello__", "_abcoll", "_bsddb", "_codecs_cn", "_codecs_hk", "_codecs_iso2022", "_codecs_jp", "_codecs_kr",
    "_codecs_tw", "_csv", "_ctypes", "_ctypes_test", "_curses", "_curses_panel", "_elementtree", "_heapq", "_hotshot", 
    "_imaging", "_imagingft", 
    "_imagingmath", "_io", "_json", "_lsprof", "_multibytecodec", "_multiprocessing", "_mysql", "_mysql_exceptions", "_psutil_linux",
    "_psutil_posix", "_pyio", "_sqlite3", "_strptime", "_testcapi", "_threading_local", "_weakrefset", "abc", "aifc", "antigravity",
    "anydbm", "argparse", 
    "ast", "asynchat", "asyncore", "atexit", "audiodev", "audioop", "base64", "bdb", "bimdp", "binhex", "bisect", "boto",
    "bsddb", "bz2", 
    "cProfile", "calendar", "cgi", "cgitb", "chaco", "chunk", "cloud", "cmd", "code", "codecs", "codeop", "collections", "colorsys", 
    "commands", "compileall", "compiler", "contextlib", "cookielib", "copy", "copy_reg", "crypt", "csv", "ctypes", "curses", 
    "cv", "cv2", "cython", "datetime", "dateutil", "dbhash", "dbm", "debconf", "decimal", "difflib", "dircache", "dis", "distutils", 
    "django", "doctest", "dumbdbm", "dummy_thread", "dummy_threading", "easy_install", "email", "enable", "encodings",
    "faulthandler", "filecmp", "fileinput", "fnmatch", "formatter", "fpectl", "fpformat", "fractions", "ftplib", "functools",
    "future_builtins", "gdal", "gdalconst", "gdalnumeric", 
    "genericpath", "getopt", "getpass", "gettext", "glob", "gzip", "h5py", "hashlib", "heapq", "hmac", "hotshot", "html5lib",
    "htmlentitydefs", "htmllib", "httplib", "httplib2", "ihooks", "imaplib", "imghdr", "importlib", "imputil",
    "inspect", "io", "json", "keyword", "kiva", "lib2to3", "linecache", "linuxaudiodev", "locale", "logging", "lsb_release", "lxml",
    "macpath", "macurl2path", "mailbox", "mailcap", "markupbase", "matplotlib", "md5", "mdp", "mhlib", "mimetools", "mimetypes", "mimify",
    "mmap", "modulefinder", "mpl_toolkits", "multifile", "multiprocessing", "mutex",
    "netrc", "new", "nis", "nltk", "nntplib", "ntpath", "nturl2path", "numbers", "numexpr", "numpy", "ogr",
    "opcode", "optparse", "os", "os2emxpath", "osgeo", "osr", "ossaudiodev", "oursql", "pandas", 
    "paramiko", "parser", "pdb", "pickle", "pickletools", "pip", "pipes", "pkg_resources", "pkgutil", "platform", "plistlib",
    "ply", "popen2", "poplib", "posixfile", "posixpath", "pprint", "profile",
    "pstats", "psutil", "psycopg2", "pty", "py_compile", "pyclbr", "pydoc", "pydoc_data", "pyexpat", "pyface", "pyfits", 
    "pyflakes", "pyglet", "pylab", "pymc", "pyopencv", "pytz", "pyximport", "quopri", "random", "re", "readline", 
    "repr", "resource", "rexec", "rfc822", "rlcompleter", "robotparser", "rpy2", "runpy", "sched", 
    "scikits", "scipy", "sets", "setuptools", "sgmllib", "sha", "shelve", "shlex", "shutil", "simplejson", 
    "site", "sitecustomize", "skimage", "smtpd", "smtplib", "sndhdr", "socket", "sqlalchemy", "sqlite3", "sre", 
    "sre_compile", "sre_constants", "sre_parse", "ssl", "stat", "statvfs", "storm", "string", "stringold", "stringprep", 
    "struct", "subprocess", "sunau", "sunaudio", "symbol", "sympy", "symtable", "sysconfig", "tables", "tabnanny", "tarfile", 
    "telnetlib", "tempfile", "termios", "test", "textwrap", "this", "threading", "timeit", "toaiff", "token", "tokenize", "trace", 
    "traceback", "traits", "traitsui", "tty", "twisted", "types", "unittest", "urllib", "urllib2", "urlparse", "user", "uu", "uuid", 
    "warnings", "wave", "weakref", "webbrowser", "whichdb", "wsgiref", "xdrlib", "xml", "xmllib", "xmlrpclib", "yaml", "zipfile", "zmq"
]

